### ISSUE TITLE
[Crawler] Initialize crawler feature

### ISSUE THREAD

**Issue by nhuannguyen96** [vh-Vu/Web-Novel-Crawler#4]
**Develop the crawler:**

- Can parse the URL and get the novel title
- Can get the chapter list and chapter title

</hr>

**Folder Structure:**
- Put in /crawler directory

</hr>

**Extension UI:**
Add novel information in extension UI box:
    - Novel title
    - Total chapter number
    - Author name (optional)
    - List of chapter and title

**Bug fix**
Fix text layout issue in #1 

</hr>

**Comment by vh-Vu** [comment]
Why get chapter list and chapter title? the UI cannot show all these things
